# Generated by Django 5.1.2 on 2024-10-24 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher'), ('guest', 'Guest'), ('admin', 'Admin')], default='guest', max_length=10),
        ),
    ]
