# Generated by Django 5.1.2 on 2024-10-26 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_profile_profileimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profileImage',
            field=models.ImageField(default='default-profile.png', upload_to='profile_images/'),
        ),
    ]
